on:
  push:
    tags:
    - 'v*'

name: Create release

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: 'Tar files'
        run: |
          zip -r windows.zip artifacts/build-windows-latest
          tar -cvf ubuntu.tar artifacts/build-ubuntu-latest

      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows.zip
            ubuntu.tar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
